server:
  servlet:
    context-path: "/grandchild-svc"
  port: 5050

spring:
  application:
    name: "Grandchild"
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

management:
  tracing:
    brave:
      span-joining-supported: true
    sampling:
      probability: 1.0
    propagation:
      type: B3_MULTI
